Algoritmo "exerc12"
// Disciplina   : Lógica de Programação
// Professor   : Joilson
// Descrição   : Conversão da temperatura em F para Celsius
// Autor(a)    : Jenifer
// Data atual  : 03/09/2024
Var
// Seção de Declarações das variáveis
tempF, tempC: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreval("Digite a atemoeratura em Fahrenheit: ")
leia(tempF)
tempC<-(tempF - 32.0)*5/9
escreval("A temperatura em Celsius e: ", tempC)
Fimalgoritmo